version: '3.8'

services:
  db_container:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "mydb"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app_container:
    build: .
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_container:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8085
    depends_on:
      - db_container
    ports:
      - "8085:8085"

volumes:
  db_data:

